=== girija1234567/oneone/Google_Calendar-v3/schemas/aclListResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "etag" : {
      "type" : "string" ,
      "required" : false
    } ,
    "nextPageToken" : {
      "type" : "string" ,
      "required" : false
    } ,
    "nextSyncToken" : {
      "type" : "string" ,
      "required" : false
    } ,
    "items" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "kind" : {
              "type" : "string" ,
              "required" : false
            } ,
            "etag" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "scope" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "type" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "value" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "role" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    }
  }
}

=== girija1234567/oneone/Google_Calendar-v3/examples/settingsResponse-example.json
{
  "kind" : "calendar#settings" ,
  "etag" : "etag" ,
  "nextPageToken" : "string" ,
  "nextSyncToken" : "string" ,
  "items" : [
    {
      "kind" : "calendar#setting" ,
      "etag" : "etag" ,
      "id" : "string" ,
      "value" : "string"
    } , {
      "kind" : "calendar#setting" ,
      "etag" : "etag" ,
      "id" : "string" ,
      "value" : "string"
    }
  ]
}

=== girija1234567/oneone/Google_Calendar-v3/examples/aclListResponse-example.json
{
  "kind" : "calendar#acl" ,
  "etag" : "etag" ,
  "nextPageToken" : "string" ,
  "nextSyncToken" : "string" ,
  "items" : [
    {
      "kind" : "calendar#aclRule" ,
      "etag" : "etag" ,
      "id" : "string" ,
      "scope" : {
        "type" : "string" ,
        "value" : "string"
      } ,
      "role" : "string"
    } , {
      "kind" : "calendar#aclRule" ,
      "etag" : "etag" ,
      "id" : "string" ,
      "scope" : {
        "type" : "string" ,
        "value" : "string"
      } ,
      "role" : "string"
    }
  ]
}

=== girija1234567/oneone/Google_Calendar-v3/examples/calendarListResponse-example.json
{
  "kind" : "calendar#calendarList" ,
  "etag" : "etag" ,
  "nextPageToken" : "string" ,
  "nextSyncToken" : "string" ,
  "items" : [
    {
      "kind" : "calendar#calendarListEntry" ,
      "etag" : "etag" ,
      "id" : "string" ,
      "summary" : "string" ,
      "description" : "string" ,
      "location" : "string" ,
      "timeZone" : "string" ,
      "summaryOverride" : "string" ,
      "colorId" : "string" ,
      "backgroundColor" : "string" ,
      "foregroundColor" : "string" ,
      "hidden" : "boolean" ,
      "selected" : "boolean" ,
      "accessRole" : "string" ,
      "defaultReminders" : [
        {
          "method" : "string" ,
          "minutes" : "integer"
        }
      ] ,
      "notificationSettings" : {
        "notifications" : [
          {
            "type" : "string" ,
            "method" : "string"
          }
        ]
      } ,
      "primary" : "boolean" ,
      "deleted" : "boolean"
    }
  ]
}
