=== girija1234567/oneone/Google_Calendar-v3/schemas/createUserCalendarRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "colorId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "backgroundColor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "foregroundColor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "hidden" : {
      "type" : "string" ,
      "required" : false
    } ,
    "selected" : {
      "type" : "string" ,
      "required" : false
    } ,
    "defaultReminders" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "method" : {
              "type" : "string" ,
              "required" : false
            } ,
            "minutes" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "notificationSettings" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "notifications" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "type" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "method" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        }
      }
    }
  }
}

=== girija1234567/oneone/Google_Calendar-v3/examples/createUserCalendarRequest-example.json
{
  "id" : "string" ,
  "colorId" : "string" ,
  "backgroundColor" : "string" ,
  "foregroundColor" : "string" ,
  "hidden" : "boolean" ,
  "selected" : "boolean" ,
  "defaultReminders" : [
    {
      "method" : "string" ,
      "minutes" : "integer"
    }
  ] ,
  "notificationSettings" : {
    "notifications" : [
      {
        "type" : "string" ,
        "method" : "string"
      }
    ]
  }
}
