=== girija1234567/oneone/Google_Calendar-v3/schemas/instancesResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "kind" : {
      "type" : "string" ,
      "required" : false
    } ,
    "etag" : {
      "type" : "string" ,
      "required" : false
    } ,
    "summary" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updated" : {
      "type" : "string" ,
      "required" : false
    } ,
    "timeZone" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessRole" : {
      "type" : "string" ,
      "required" : false
    } ,
    "defaultReminders" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "method" : {
              "type" : "string" ,
              "required" : false
            } ,
            "minutes" : {
              "type" : "number" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "nextSyncToken" : {
      "type" : "string" ,
      "required" : false
    } ,
    "items" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "kind" : {
              "type" : "string" ,
              "required" : false
            } ,
            "etag" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "status" : {
              "type" : "string" ,
              "required" : false
            } ,
            "htmlLink" : {
              "type" : "string" ,
              "required" : false
            } ,
            "created" : {
              "type" : "string" ,
              "required" : false
            } ,
            "updated" : {
              "type" : "string" ,
              "required" : false
            } ,
            "creator" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "email" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "displayName" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "organizer" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "email" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "displayName" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "self" : {
                  "type" : "boolean" ,
                  "required" : false
                }
              }
            } ,
            "start" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "dateTime" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "timeZone" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "end" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "dateTime" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "timeZone" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "iCalUID" : {
              "type" : "string" ,
              "required" : false
            } ,
            "sequence" : {
              "type" : "number" ,
              "required" : false
            } ,
            "attendees" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "email" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "displayName" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "responseStatus" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                }
              ]
            } ,
            "reminders" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "useDefault" : {
                  "type" : "boolean" ,
                  "required" : false
                } ,
                "overrides" : {
                  "type" : "array" ,
                  "required" : false ,
                  "items" : [
                    {
                      "type" : "object" ,
                      "properties" : {
                        "method" : {
                          "type" : "string" ,
                          "required" : false
                        } ,
                        "minutes" : {
                          "type" : "number" ,
                          "required" : false
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

=== girija1234567/oneone/Google_Calendar-v3/examples/instancesResponse-example.json
{
 "kind": "calendar#events",
 "etag": "\"1427205872938000\"",
 "summary": "testNotebookCalendar",
 "description": "testNotebookCalendar",
 "updated": "2015-03-24T14:04:32.938Z",
 "timeZone": "UTC",
 "accessRole": "owner",
 "defaultReminders": [
  {
   "method": "popup",
   "minutes": 30
  }
 ],
 "nextSyncToken": "CJDYz5iUwcQCEJDYz5iUwcQCGAU=",
 "items": [
  {
   "kind": "calendar#event",
   "etag": "\"2854411743743000\"",
   "id": "6q6budag2hd07c0fm99hf1r8ro",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=NnE2YnVkYWcyaGQwN2MwZm05OWhmMXI4cm8gdTdtaWdmZzFpcGRpODIwZjhkMDgzMnUxdjRAZw",
   "created": "2015-03-24T14:04:31.000Z",
   "updated": "2015-03-24T14:04:31.954Z",
   "creator": {
    "email": "ramltest3@gmail.com",
    "displayName": "Raml Test"
   },
   "organizer": {
    "email": "u7migfg1ipdi820f8d0832u1v4@group.calendar.google.com",
    "displayName": "testNotebookCalendar",
    "self": true
   },
   "start": {
    "dateTime": "2014-11-21T10:28:20Z",
    "timeZone": "UTC"
   },
   "end": {
    "dateTime": "2014-11-21T11:29:20Z",
    "timeZone": "UTC"
   },
   "iCalUID": "6q6budag2hd07c0fm99hf1r8ro@google.com",
   "sequence": 0,
   "attendees": [
    {
     "email": "ramltest3@gmail.com",
     "displayName": "Raml Test",
     "responseStatus": "needsAction"
    }
   ],
   "reminders": {
    "useDefault": false,
    "overrides": [
     {
      "method": "popup",
      "minutes": 0
     }
    ]
   }
  }
 ]
}
